# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-03 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0004_auto_20190802_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_image'),
        ),
    ]
