# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-03 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0005_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
